import styles from "../styles/pages/Home.module.css";
import Head from "next/head";
import Socials from "../components/Socials";

function Intro() {
    return (
        <div id={`intro`} className={`${styles.intro} d-flex-col-l gap-2`}>
            <h1 className={`fw-2 fs-lg mt-5`}>Hi, I&#39;m <span className={`fw-6`}>Jonathan Nguyen</span></h1>
            <p className={`fw-2 fs-sm`}>
                I&#39;m a full stack software developer studying at the
                University of Notre Dame. I have developed several
                web app solutions during my time at Notre Dame and have a particular
                interest in <span className={"fw-5"}>cryptography and information security</span> -
                specifically pentesting, data encryption, and security response.
            </p>
            <p className={`fw-2 fs-sm`}>
                Currently, I am developing a secure and efficient decentralized
                alternative to multimedia copyrighting.
            </p>
            <Socials size={32} gap={4} margin={2}/>
        </div>
    );
}

function About() {
    return (
        <div id={`about`} className={`${styles.about} gap-2`}>
            <h2 className={`fw-6 fs-md`}>about.</h2>
            <p className={`${styles.description} fw-2 fs-sm`}>
                Aside from academics, I love doing four things in life: being outdoors, playing guitar,
                photography, and being with close friends. Feel free to explore below to learn more
                about me.
            </p>
            <div className={`${styles.grid} gap-2`}>
                <div className={`${styles.gridItem}`} style={{gridColumn: `span 6`, gridRow: `span 3`}}>Main 1</div>
                <div className={`${styles.gridItem}`} style={{gridColumn: `span 6`, gridRow: `span 3`}}>Main 2</div>
                <div className={`${styles.gridItem}`} style={{gridColumn: `span 4`, gridRow: `span 2`}}>Side 1</div>
                <div className={`${styles.gridItem}`} style={{gridColumn: `span 4`, gridRow: `span 2`}}>Side 2</div>
                <div className={`${styles.gridItem}`} style={{gridColumn: `span 4`, gridRow: `span 2`}}>Side 3</div>
            </div>
            <p className={`${styles.description} fw-2 fs-xs`}>
                Damien, Chase, TJ, Chuck, Ready, Dom, Cat, Andrea, Andrew, Tmerc, Brooke, Peter, Ryan, Mary, Annie,
                Tara, Conor, Peter, Mikey, Griff, Dylan, DLM, Keaton, Rory, Ian, Emilio, Soph, Maddie, Chloe, Mary,
                Anna, Tommy, or Holly: If you&#39;re reading this, you&#39;re the best
            </p>
        </div>
    )
}

function Projects() {
    return (
        <div id={`projects`} className={`${styles.projects}`}>
            <h2 className={`fw-6`}>projects.</h2>
        </div>
    );
}

function Experience() {
    return (
        <div id={`experience`} className={`${styles.experience}`}>
            <h2 className={`fw-6`}>experience.</h2>
        </div>
    );
}

function index() {
    return (
        <div>
            <Head>
                <title>Jonathan Nguyen</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/media/icons/favicon.png" />
            </Head>
            <main>
                <Intro/>
                <About/>
                <Projects/>
                <Experience/>
            </main>
        </div>
    )
}

export default index;
