import styles from "../styles/pages/Home.module.css";
import Head from "next/head";
import Socials from "../components/Socials";
import {useEffect} from "react";

function Intro() {
    return (
        <div id={`intro`} className={`${styles.intro} d-flex-col-l gap-2`}>
            <h1 className={`fw-2 fs-lg mt-5`}>Hi, I&#39;m <span className={`fw-6`}>Jonathan Nguyen</span></h1>
            <p className={`fw-2 fs-sm`}>
                I&#39;m a full stack software developer studying at the
                University of Notre Dame. I have developed several
                web app solutions during my time at Notre Dame and have a particular
                interest in cryptography and information security
                - specifically pentesting, data encryption, and security response.
            </p>
            <Socials/>
        </div>
    );
}

function About() {
    return (
        <div id={`about`} className={`${styles.about} gap-2`}>
            <h2 className={`fw-6`}>about.</h2>
            <p className={`fw-2 fs-sm`}>
                Aside from academics, I love 4 things in life: The Outdoors, playing Guitar,
            </p>
        </div>
    )
}

function Projects() {
    return (
        <div id={`projects`} className={`${styles.projects}`}>
            <h2 className={`fw-6`}>projects.</h2>
        </div>
    );
}

function Experience() {
    return (
        <div id={`experience`} className={`${styles.experience}`}>
            <h2 className={`fw-6`}>experience.</h2>
        </div>
    );
}

export default function index() {
    return (
        <div>
            <Head>
                <title>Jonathan Nguyen</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/media/icons/favicon.png" />
            </Head>
            <main>
                <Intro/>
                <About/>
                <Projects/>
                <Experience/>
            </main>
        </div>
    )
}
